### PR TITLE
Fix minor issues in main.go (from golint).

### PR DESCRIPTION
**Pull request by marcopaganini**

### CODE REVIEW

**Comment by antonmedv** [comment]
Not sure what this pr fixes, besides code style.

**Comment by marcopaganini** [comment]
It basically makes go linting tools happy. They're very commonly used in Go to detect all sorts of problems and code simplifications. There should be no change in the program itself, just make it a bit more concise and readable.

**Comment by antonmedv** [comment]
Well) I like my code more the one linter produces in this specific case.

**Comment by marcopaganini** [comment]
No worries! Just reject the PR. 😁

**Pull request closed without merging**
